# Generated by Django 4.2.11 on 2024-04-08 03:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tester_bomb_score_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_code', models.CharField(max_length=100)),
                ('current_round', models.IntegerField(default=0)),
                ('score_1', models.IntegerField(default=0)),
                ('score_2', models.IntegerField(default=0)),
                ('score_3', models.IntegerField(default=0)),
                ('score_4', models.IntegerField(default=0)),
                ('score_5', models.IntegerField(default=0)),
                ('bomb_1', models.IntegerField(default=9)),
                ('bomb_2', models.IntegerField(default=38)),
                ('bomb_3', models.IntegerField(default=44)),
                ('bomb_4', models.IntegerField(default=36)),
                ('bomb_5', models.IntegerField(default=38)),
                ('last_modify_date', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tester_bomb_score',
            },
        ),
        migrations.CreateModel(
            name='tester_char_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_code', models.CharField(max_length=100)),
                ('tester_password', models.CharField(max_length=100)),
                ('tester_name', models.CharField(max_length=100)),
                ('tester_birthday', models.CharField(max_length=100)),
                ('tester_gender', models.CharField(max_length=100)),
                ('tester_company', models.CharField(max_length=100)),
                ('tester_position', models.CharField(max_length=100)),
                ('tester_jobtype', models.CharField(max_length=100)),
                ('tester_workyear', models.CharField(max_length=100)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tester_char',
            },
        ),
        migrations.CreateModel(
            name='tester_numerosity_score_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_code', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tester_numerosity_score',
            },
        ),
        migrations.CreateModel(
            name='tester_set_score_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_code', models.CharField(max_length=100)),
                ('correct', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('wrong', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('answered_count', models.IntegerField(default=0)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tester_char_db')),
            ],
            options={
                'db_table': 'tester_set_score',
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('stay_time', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tester_char_db')),
            ],
        ),
    ]
