# Generated by Django 4.2.11 on 2024-04-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester_bomb_score_db',
            name='bomb_1',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='tester_bomb_score_db',
            name='bomb_2',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='tester_bomb_score_db',
            name='bomb_3',
            field=models.IntegerField(default=43),
        ),
        migrations.AlterField(
            model_name='tester_bomb_score_db',
            name='bomb_4',
            field=models.IntegerField(default=43),
        ),
        migrations.AlterField(
            model_name='tester_bomb_score_db',
            name='bomb_5',
            field=models.IntegerField(default=43),
        ),
    ]
